//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaserPieceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorAndProduct
    {
        public int id { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> productid { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
    }
}
