//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaserPieceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payemnt_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<System.DateTime> Payemnt_Date { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Address { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Order Order { get; set; }
    }
}
